---
- name: Create Openstack with Kolla
  hosts: localhost
  connection: local
  become: True
  gather_facts: True
  roles:
    - setup_kolla_ansible
    #- run_kolla_ansible
    
- name: Deploy servers via Bifrost
  hosts: localhost
  connection: local
  gather_facts: False
  
  roles:
  - bifrost

- name: Run post-install tasks on deployed servers
  hosts: kolla-*
  gather_facts: False
  
  roles:
  - post-install

- name: Deploy kolla using kolla-ansible
  hosts: localhost
  connection: local
  gather_facts: False
  
  roles:
  - kolla

- name: Post fixing of kolla-ansible deployment
  hosts: kolla-*
  gather_facts: False

  roles:
  - post-kolla
